# Generated by Django 4.2.14 on 2024-08-20 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bk',
            fields=[
                ('bk_no', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pd_id', models.ManyToManyField(to='product.product', verbose_name='Restaurants')),
                ('user', models.ForeignKey(db_column='user', default='admin@admin.com', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Bk',
                'verbose_name_plural': 'Bks',
                'db_table': 'bk',
            },
        ),
    ]
