# Generated by Django 4.2.14 on 2024-08-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_alter_bk_pd_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bk',
            name='bk_no',
            field=models.CharField(default='c63d3fd8-5820-4588-be77-0ef0c5ac4f6f', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
