# Generated by Django 4.2.14 on 2024-10-01 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='url',
        ),
    ]
