# Generated by Django 4.2.14 on 2024-09-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
