# Generated by Django 4.2.14 on 2024-09-29 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='url',
        ),
    ]
