# Generated by Django 4.2.14 on 2024-09-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_rename_image_review_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='url',
            new_name='image',
        ),
    ]
